# Generated by Django 2.0.2 on 2018-03-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='create_at',
        ),
    ]
