# Generated by Django 2.0.2 on 2018-03-13 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 13, 10, 57, 47, 748056, tzinfo=utc)),
        ),
    ]
